/**
 * Phone number configuration
 * Centralized configuration for phone number handling
 * Sources: ITU, Regulatory Authorities (ART Cameroon, ARTP Senegal, etc.)
 */

export interface Country {
  name: string;
  code: string;
  flag: string;
  digits: number[]; // Array of valid lengths (excl. country code)
  prefixes?: string[]; // Valid prefixes (start of local number)
  format: string; // Format mask using '#' for digits
}

export const COUNTRIES: Country[] = [
  {
    name: "Afghanistan",
    code: '+93',
    flag: '🇦🇫',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Aland Islands",
    code: '+358',
    flag: '🇦🇽',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Albania",
    code: '+355',
    flag: '🇦🇱',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Algeria",
    code: '+213',
    flag: '🇩🇿',
    digits: [9],
    format: '## ### ## ##',
  },
  {
    name: "American Samoa",
    code: '+1',
    flag: '🇦🇸',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Andorra",
    code: '+376',
    flag: '🇦🇩',
    digits: [6],
    format: '### ###',
  },
  {
    name: "Angola",
    code: '+244',
    flag: '🇦🇴',
    digits: [9],
    format: '### ### ###',
  },
  {
    name: "Anguilla",
    code: '+1',
    flag: '🇦🇮',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Antarctica",
    code: '+672',
    flag: '🇦🇶',
    digits: [6],
    format: '# ## ###',
  },
  {
    name: "Antigua And Barbuda",
    code: '+1',
    flag: '🇦🇬',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Argentina",
    code: '+54',
    flag: '🇦🇷',
    digits: [10],
    format: '# ## ###-####',
  },
  {
    name: "Armenia",
    code: '+374',
    flag: '🇦🇲',
    digits: [8],
    format: '## ### ###',
  },
  {
    name: "Aruba",
    code: '+297',
    flag: '🇦🇼',
    digits: [7],
    format: '### ####',
  },
  {
    name: "Australia",
    code: '+61',
    flag: '🇦🇺',
    digits: [9],
    format: '# #### ####',
  },
  {
    name: "Austria",
    code: '+43',
    flag: '🇦🇹',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Azerbaijan",
    code: '+994',
    flag: '🇦🇿',
    digits: [9],
    format: '## ### ## ##',
  },
  {
    name: "Bahamas",
    code: '+1',
    flag: '🇧🇸',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Bahrain",
    code: '+973',
    flag: '🇧🇭',
    digits: [8],
    format: '#### ####',
  },
  {
    name: "Bangladesh",
    code: '+880',
    flag: '🇧🇩',
    digits: [7, 8],
    format: '# ### ####',
  },
  {
    name: "Barbados",
    code: '+1',
    flag: '🇧🇧',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Belarus",
    code: '+375',
    flag: '🇧🇾',
    digits: [9],
    format: '(##) ###-##-##',
  },
  {
    name: "Belgium",
    code: '+32',
    flag: '🇧🇪',
    digits: [8],
    format: '# ### ## ##',
  },
  {
    name: "Belize",
    code: '+501',
    flag: '🇧🇿',
    digits: [7],
    format: '###-####',
  },
  {
    name: "Benin",
    code: '+229',
    flag: '🇧🇯',
    digits: [8],
    format: '## ## ####',
  },
  {
    name: "Bermuda",
    code: '+1',
    flag: '🇧🇲',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Bhutan",
    code: '+975',
    flag: '🇧🇹',
    digits: [7],
    format: '# ### ###',
  },
  {
    name: "Bolivia",
    code: '+591',
    flag: '🇧🇴',
    digits: [8],
    format: '# ### ####',
  },
  {
    name: "Bosnia And Herzegovina",
    code: '+387',
    flag: '🇧🇦',
    digits: [8, 9],
    format: '## ###-####',
  },
  {
    name: "Botswana",
    code: '+267',
    flag: '🇧🇼',
    digits: [8],
    format: '## ### ###',
  },
  {
    name: "Bouvet Island",
    code: '+47',
    flag: '🇧🇻',
    digits: [8],
    format: '### ## ###',
  },
  {
    name: "Brazil",
    code: '+55',
    flag: '🇧🇷',
    digits: [10, 11],
    format: '## #### #####',
  },
  {
    name: "British Indian Ocean Territory",
    code: '+246',
    flag: '🇮🇴',
    digits: [7],
    format: '### ####',
  },
  {
    name: "Brunei Darussalam",
    code: '+673',
    flag: '🇧🇳',
    digits: [7],
    format: '### ####',
  },
  {
    name: "Bulgaria",
    code: '+359',
    flag: '🇧🇬',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Burkina Faso",
    code: '+226',
    flag: '🇧🇫',
    digits: [8],
    format: '## ## ####',
  },
  {
    name: "Burundi",
    code: '+257',
    flag: '🇧🇮',
    digits: [8],
    format: '## ## ####',
  },
  {
    name: "Cambodia",
    code: '+855',
    flag: '🇰🇭',
    digits: [8],
    format: '## ### ###',
  },
  {
    name: "Cameroon",
    code: '+237',
    flag: '🇨🇲',
    digits: [9],
    format: '# ## ## ## ##',
  },
  {
    name: "Canada",
    code: '+1',
    flag: '🇨🇦',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Cape Verde",
    code: '+238',
    flag: '🇨🇻',
    digits: [6],
    format: '(##) ## ##',
  },
  {
    name: "Cayman Islands",
    code: '+1',
    flag: '🇰🇾',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Central African Republic",
    code: '+236',
    flag: '🇨🇫',
    digits: [8],
    format: '## ## ####',
  },
  {
    name: "Chad",
    code: '+235',
    flag: '🇹🇩',
    digits: [8],
    format: '## ## ## ##',
  },
  {
    name: "Chile",
    code: '+56',
    flag: '🇨🇱',
    digits: [9],
    format: '# #### ####',
  },
  {
    name: "China",
    code: '+86',
    flag: '🇨🇳',
    digits: [10],
    format: '## #### ####',
  },
  {
    name: "Christmas Island",
    code: '+61',
    flag: '🇨🇽',
    digits: [9],
    format: '# ## ### ###',
  },
  {
    name: "Cocos (Keeling) Islands",
    code: '+61',
    flag: '🇨🇨',
    digits: [9],
    format: '# ## ### ###',
  },
  {
    name: "Colombia",
    code: '+57',
    flag: '🇨🇴',
    digits: [8],
    format: '# ### ####',
  },
  {
    name: "Comoros",
    code: '+269',
    flag: '🇰🇲',
    digits: [6],
    format: '## ## ##',
  },
  {
    name: "Congo",
    code: '+242',
    flag: '🇨🇬',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Congo, Democratic Republic",
    code: '+243',
    flag: '🇨🇩',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Cook Islands",
    code: '+682',
    flag: '🇨🇰',
    digits: [5],
    format: '## ###',
  },
  {
    name: "Costa Rica",
    code: '+506',
    flag: '🇨🇷',
    digits: [8],
    format: '#### ####',
  },
  {
    name: "Cote D'Ivoire",
    code: '+225',
    flag: '🇨🇮',
    digits: [8],
    format: '## ## ## ##',
  },
  {
    name: "Croatia",
    code: '+385',
    flag: '🇭🇷',
    digits: [8],
    format: '# ### ####',
  },
  {
    name: "Cuba",
    code: '+53',
    flag: '🇨🇺',
    digits: [8],
    format: '# ### ####',
  },
  {
    name: "Cyprus",
    code: '+357',
    flag: '🇨🇾',
    digits: [8],
    format: '## ### ###',
  },
  {
    name: "Czech Republic",
    code: '+420',
    flag: '🇨🇿',
    digits: [9],
    format: '### ### ###',
  },
  {
    name: "Denmark",
    code: '+45',
    flag: '🇩🇰',
    digits: [8],
    format: '## ## ## ##',
  },
  {
    name: "Djibouti",
    code: '+253',
    flag: '🇩🇯',
    digits: [8],
    format: '## ## ## ##',
  },
  {
    name: "Dominica",
    code: '+1',
    flag: '🇩🇲',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Dominican Republic",
    code: '+1',
    flag: '🇩🇴',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Ecuador",
    code: '+593',
    flag: '🇪🇨',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Egypt",
    code: '+20',
    flag: '🇪🇬',
    digits: [9],
    format: '# #### ####',
  },
  {
    name: "El Salvador",
    code: '+503',
    flag: '🇸🇻',
    digits: [8],
    format: '#### ####',
  },
  {
    name: "Equatorial Guinea",
    code: '+240',
    flag: '🇬🇶',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Eritrea",
    code: '+291',
    flag: '🇪🇷',
    digits: [7],
    format: '# ### ###',
  },
  {
    name: "Estonia",
    code: '+372',
    flag: '🇪🇪',
    digits: [8],
    format: '#### ####',
  },
  {
    name: "Ethiopia",
    code: '+251',
    flag: '🇪🇹',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Falkland Islands (Malvinas)",
    code: '+500',
    flag: '🇫🇰',
    digits: [5],
    format: '#####',
  },
  {
    name: "Faroe Islands",
    code: '+298',
    flag: '🇫🇴',
    digits: [6],
    format: '######',
  },
  {
    name: "Fiji",
    code: '+679',
    flag: '🇫🇯',
    digits: [7],
    format: '### ####',
  },
  {
    name: "Finland",
    code: '+358',
    flag: '🇫🇮',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "France",
    code: '+33',
    flag: '🇫🇷',
    digits: [9],
    format: '# ## ## ## ##',
  },
  {
    name: "French Guiana",
    code: '+594',
    flag: '🇬🇫',
    digits: [9],
    format: '##### ####',
  },
  {
    name: "French Polynesia",
    code: '+689',
    flag: '🇵🇫',
    digits: [6],
    format: '## ## ##',
  },
  {
    name: "French Southern Territories",
    code: '+262',
    flag: '🇹🇫',
    digits: [9],
    format: '##### ####',
  },
  {
    name: "Gabon",
    code: '+241',
    flag: '🇬🇦',
    digits: [7],
    format: '# ## ## ##',
  },
  {
    name: "Gambia",
    code: '+220',
    flag: '🇬🇲',
    digits: [7],
    format: '### ####',
  },
  {
    name: "Georgia",
    code: '+995',
    flag: '🇬🇪',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Germany",
    code: '+49',
    flag: '🇩🇪',
    digits: [8],
    format: '## ######',
  },
  {
    name: "Ghana",
    code: '+233',
    flag: '🇬🇭',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Gibraltar",
    code: '+350',
    flag: '🇬🇮',
    digits: [8],
    format: '### #####',
  },
  {
    name: "Greece",
    code: '+30',
    flag: '🇬🇷',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Greenland",
    code: '+299',
    flag: '🇬🇱',
    digits: [6],
    format: '## ## ##',
  },
  {
    name: "Grenada",
    code: '+1',
    flag: '🇬🇩',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Guadeloupe",
    code: '+590',
    flag: '🇬🇵',
    digits: [8],
    format: '#### ####',
  },
  {
    name: "Guam",
    code: '+1',
    flag: '🇬🇺',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Guatemala",
    code: '+502',
    flag: '🇬🇹',
    digits: [8],
    format: '# ### ####',
  },
  {
    name: "Guernsey",
    code: '+44',
    flag: '🇬🇬',
    digits: [10],
    format: '#### ## ####',
  },
  {
    name: "Guinea",
    code: '+224',
    flag: '🇬🇳',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Guinea-Bissau",
    code: '+245',
    flag: '🇬🇼',
    digits: [7],
    format: '# ### ###',
  },
  {
    name: "Guyana",
    code: '+592',
    flag: '🇬🇾',
    digits: [7],
    format: '### ####',
  },
  {
    name: "Haiti",
    code: '+509',
    flag: '🇭🇹',
    digits: [8],
    format: '## ## ####',
  },
  {
    name: "Heard Island & Mcdonald Islands",
    code: '+672',
    flag: '🇭🇲',
    digits: [6],
    format: '# ## ###',
  },
  {
    name: "Holy See (Vatican City State)",
    code: '+39',
    flag: '🇻🇦',
    digits: [10],
    format: '## ### #####',
  },
  {
    name: "Honduras",
    code: '+504',
    flag: '🇭🇳',
    digits: [8],
    format: '#### ####',
  },
  {
    name: "Hong Kong",
    code: '+852',
    flag: '🇭🇰',
    digits: [8],
    format: '#### ####',
  },
  {
    name: "Hungary",
    code: '+36',
    flag: '🇭🇺',
    digits: [7, 9],
    format: '## ### ####',
  },
  {
    name: "Iceland",
    code: '+354',
    flag: '🇮🇸',
    digits: [7],
    format: '### ####',
  },
  {
    name: "India",
    code: '+91',
    flag: '🇮🇳',
    digits: [10],
    format: '## #### ####',
  },
  {
    name: "Indonesia",
    code: '+62',
    flag: '🇮🇩',
    digits: [10],
    format: '## #### ####',
  },
  {
    name: "Iran, Islamic Republic Of",
    code: '+98',
    flag: '🇮🇷',
    digits: [10],
    format: '## #### ####',
  },
  {
    name: "Iraq",
    code: '+964',
    flag: '🇮🇶',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Ireland",
    code: '+353',
    flag: '🇮🇪',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Isle Of Man",
    code: '+44',
    flag: '🇮🇲',
    digits: [10],
    format: '#### ######',
  },
  {
    name: "Israel",
    code: '+972',
    flag: '🇮🇱',
    digits: [8],
    format: '# ### ####',
  },
  {
    name: "Italy",
    code: '+39',
    flag: '🇮🇹',
    digits: [10],
    format: '## #### ####',
  },
  {
    name: "Jamaica",
    code: '+1',
    flag: '🇯🇲',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Japan",
    code: '+81',
    flag: '🇯🇵',
    digits: [10],
    format: '##-####-####',
  },
  {
    name: "Jersey",
    code: '+44',
    flag: '🇯🇪',
    digits: [10],
    format: '#### ######',
  },
  {
    name: "Jordan",
    code: '+962',
    flag: '🇯🇴',
    digits: [9],
    format: '# #### ####',
  },
  {
    name: "Kazakhstan",
    code: '+7',
    flag: '🇰🇿',
    digits: [10],
    format: '### ### ####',
  },
  {
    name: "Kenya",
    code: '+254',
    flag: '🇰🇪',
    digits: [9],
    format: '## #######',
  },
  {
    name: "Kiribati",
    code: '+686',
    flag: '🇰🇮',
    digits: [5],
    format: '## ###',
  },
  {
    name: "Korea",
    code: '+82',
    flag: '🇰🇷',
    digits: [10],
    format: '##-####-####',
  },
  {
    name: "Kuwait",
    code: '+965',
    flag: '🇰🇼',
    digits: [8],
    format: '#### ####',
  },
  {
    name: "Kyrgyzstan",
    code: '+996',
    flag: '🇰🇬',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Lao People's Democratic Republic",
    code: '+856',
    flag: '🇱🇦',
    digits: [8],
    format: '## ### ###',
  },
  {
    name: "Latvia",
    code: '+371',
    flag: '🇱🇻',
    digits: [8],
    format: '#### ####',
  },
  {
    name: "Lebanon",
    code: '+961',
    flag: '🇱🇧',
    digits: [7],
    format: '# ### ###',
  },
  {
    name: "Lesotho",
    code: '+266',
    flag: '🇱🇸',
    digits: [8],
    format: '# ### ####',
  },
  {
    name: "Liberia",
    code: '+231',
    flag: '🇱🇷',
    digits: [8],
    format: '## ### ###',
  },
  {
    name: "Libyan Arab Jamahiriya",
    code: '+218',
    flag: '🇱🇾',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Liechtenstein",
    code: '+423',
    flag: '🇱🇮',
    digits: [7],
    format: '### ####',
  },
  {
    name: "Lithuania",
    code: '+370',
    flag: '🇱🇹',
    digits: [8],
    format: '### #####',
  },
  {
    name: "Luxembourg",
    code: '+352',
    flag: '🇱🇺',
    digits: [9],
    format: '### ### ###',
  },
  {
    name: "Macao",
    code: '+853',
    flag: '🇲🇴',
    digits: [8],
    format: '#### ####',
  },
  {
    name: "Macedonia",
    code: '+389',
    flag: '🇲🇰',
    digits: [8],
    format: '## ### ###',
  },
  {
    name: "Madagascar",
    code: '+261',
    flag: '🇲🇬',
    digits: [9],
    format: '## ## #####',
  },
  {
    name: "Malawi",
    code: '+265',
    flag: '🇲🇼',
    digits: [8],
    format: '# ### ####',
  },
  {
    name: "Malaysia",
    code: '+60',
    flag: '🇲🇾',
    digits: [9],
    format: '##-### ####',
  },
  {
    name: "Maldives",
    code: '+960',
    flag: '🇲🇻',
    digits: [7],
    format: '###-####',
  },
  {
    name: "Mali",
    code: '+223',
    flag: '🇲🇱',
    digits: [8],
    format: '## ## ####',
  },
  {
    name: "Malta",
    code: '+356',
    flag: '🇲🇹',
    digits: [8],
    format: '#### ####',
  },
  {
    name: "Marshall Islands",
    code: '+692',
    flag: '🇲🇭',
    digits: [7],
    format: '###-####',
  },
  {
    name: "Martinique",
    code: '+596',
    flag: '🇲🇶',
    digits: [7],
    format: '### ## ##',
  },
  {
    name: "Mauritania",
    code: '+222',
    flag: '🇲🇷',
    digits: [8],
    format: '## ## ####',
  },
  {
    name: "Mauritius",
    code: '+230',
    flag: '🇲🇺',
    digits: [7],
    format: '### ####',
  },
  {
    name: "Mayotte",
    code: '+262',
    flag: '🇾🇹',
    digits: [9],
    format: '##### ####',
  },
  {
    name: "Mexico",
    code: '+52',
    flag: '🇲🇽',
    digits: [10],
    format: '## #### ####',
  },
  {
    name: "Micronesia, Federated States Of",
    code: '+691',
    flag: '🇫🇲',
    digits: [7],
    format: '### ####',
  },
  {
    name: "Moldova",
    code: '+373',
    flag: '🇲🇩',
    digits: [8],
    format: '#### ####',
  },
  {
    name: "Monaco",
    code: '+377',
    flag: '🇲🇨',
    digits: [8],
    format: '## ## ## ##',
  },
  {
    name: "Mongolia",
    code: '+976',
    flag: '🇲🇳',
    digits: [8],
    format: '## ## ####',
  },
  {
    name: "Montenegro",
    code: '+382',
    flag: '🇲🇪',
    digits: [8],
    format: '## ### ###',
  },
  {
    name: "Montserrat",
    code: '+1',
    flag: '🇲🇸',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Morocco",
    code: '+212',
    flag: '🇲🇦',
    digits: [10],
    format: '## #### ####',
  },
  {
    name: "Mozambique",
    code: '+258',
    flag: '🇲🇿',
    digits: [8],
    format: '## ### ###',
  },
  {
    name: "Myanmar",
    code: '+95',
    flag: '🇲🇲',
    digits: [8],
    format: '## ### ###',
  },
  {
    name: "Namibia",
    code: '+264',
    flag: '🇳🇦',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Nauru",
    code: '+674',
    flag: '🇳🇷',
    digits: [7],
    format: '### ####',
  },
  {
    name: "Nepal",
    code: '+977',
    flag: '🇳🇵',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Netherlands",
    code: '+31',
    flag: '🇳🇱',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "New Caledonia",
    code: '+687',
    flag: '🇳🇨',
    digits: [6],
    format: '## ####',
  },
  {
    name: "New Zealand",
    code: '+64',
    flag: '🇳🇿',
    digits: [8],
    format: '# ### ####',
  },
  {
    name: "Nicaragua",
    code: '+505',
    flag: '🇳🇮',
    digits: [8],
    format: '#### ####',
  },
  {
    name: "Niger",
    code: '+227',
    flag: '🇳🇪',
    digits: [8],
    format: '## ## ####',
  },
  {
    name: "Nigeria",
    code: '+234',
    flag: '🇳🇬',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Niue",
    code: '+683',
    flag: '🇳🇺',
    digits: [4],
    format: '####',
  },
  {
    name: "Norfolk Island",
    code: '+672',
    flag: '🇳🇫',
    digits: [5],
    format: '## ###',
  },
  {
    name: "Northern Mariana Islands",
    code: '+1',
    flag: '🇲🇵',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Norway",
    code: '+47',
    flag: '🇳🇴',
    digits: [8],
    format: '## ## ## ##',
  },
  {
    name: "Oman",
    code: '+968',
    flag: '🇴🇲',
    digits: [8],
    format: '#### ####',
  },
  {
    name: "Pakistan",
    code: '+92',
    flag: '🇵🇰',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Palau",
    code: '+680',
    flag: '🇵🇼',
    digits: [7],
    format: '### ####',
  },
  {
    name: "Palestinian Territory, Occupied",
    code: '+970',
    flag: '🇵🇸',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Panama",
    code: '+507',
    flag: '🇵🇦',
    digits: [7],
    format: '### ####',
  },
  {
    name: "Papua New Guinea",
    code: '+675',
    flag: '🇵🇬',
    digits: [8],
    format: '## ### ###',
  },
  {
    name: "Paraguay",
    code: '+595',
    flag: '🇵🇾',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Peru",
    code: '+51',
    flag: '🇵🇪',
    digits: [8],
    format: '## ### ###',
  },
  {
    name: "Philippines",
    code: '+63',
    flag: '🇵🇭',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Pitcairn",
    code: '+64',
    flag: '🇵🇳',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Poland",
    code: '+48',
    flag: '🇵🇱',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Portugal",
    code: '+351',
    flag: '🇵🇹',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Puerto Rico",
    code: '+1',
    flag: '🇵🇷',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Qatar",
    code: '+974',
    flag: '🇶🇦',
    digits: [8],
    format: '#### ####',
  },
  {
    name: "Reunion",
    code: '+262',
    flag: '🇷🇪',
    digits: [9],
    format: '##### ####',
  },
  {
    name: "Romania",
    code: '+40',
    flag: '🇷🇴',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Russian Federation",
    code: '+7',
    flag: '🇷🇺',
    digits: [10],
    format: '(###) ###-##-##',
  },
  {
    name: "Rwanda",
    code: '+250',
    flag: '🇷🇼',
    digits: [8],
    format: '## ### ###',
  },
  {
    name: "Saint Barthelemy",
    code: '+590',
    flag: '🇧🇱',
    digits: [7],
    format: '### ####',
  },
  {
    name: "Saint Helena",
    code: '+290',
    flag: '🇸🇭',
    digits: [4],
    format: '####',
  },
  {
    name: "Saint Kitts And Nevis",
    code: '+1',
    flag: '🇰🇳',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Saint Lucia",
    code: '+1',
    flag: '🇱🇨',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Saint Martin",
    code: '+590',
    flag: '🇲🇫',
    digits: [7],
    format: '### ####',
  },
  {
    name: "Saint Pierre And Miquelon",
    code: '+508',
    flag: '🇵🇲',
    digits: [6],
    format: '## ## ##',
  },
  {
    name: "Saint Vincent And Grenadines",
    code: '+1',
    flag: '🇻🇨',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Samoa",
    code: '+685',
    flag: '🇼🇸',
    digits: [6],
    format: '## ####',
  },
  {
    name: "San Marino",
    code: '+378',
    flag: '🇸🇲',
    digits: [10],
    format: '#### ######',
  },
  {
    name: "Sao Tome And Principe",
    code: '+239',
    flag: '🇸🇹',
    digits: [6],
    format: '## ## ##',
  },
  {
    name: "Saudi Arabia",
    code: '+966',
    flag: '🇸🇦',
    digits: [9],
    format: '# #### ####',
  },
  {
    name: "Senegal",
    code: '+221',
    flag: '🇸🇳',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Serbia",
    code: '+381',
    flag: '🇷🇸',
    digits: [9],
    format: '## #### ###',
  },
  {
    name: "Seychelles",
    code: '+248',
    flag: '🇸🇨',
    digits: [7],
    format: '# ### ###',
  },
  {
    name: "Sierra Leone",
    code: '+232',
    flag: '🇸🇱',
    digits: [8],
    format: '## ######',
  },
  {
    name: "Singapore",
    code: '+65',
    flag: '🇸🇬',
    digits: [8],
    format: '#### ####',
  },
  {
    name: "Slovakia",
    code: '+421',
    flag: '🇸🇰',
    digits: [8, 10],
    format: '### ### ####',
  },
  {
    name: "Slovenia",
    code: '+386',
    flag: '🇸🇮',
    digits: [8],
    format: '# ### ## ##',
  },
  {
    name: "Solomon Islands",
    code: '+677',
    flag: '🇸🇧',
    digits: [5],
    format: '#####',
  },
  {
    name: "Somalia",
    code: '+252',
    flag: '🇸🇴',
    digits: [7],
    format: '# ### ###',
  },
  {
    name: "South Africa",
    code: '+27',
    flag: '🇿🇦',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "South Georgia And Sandwich Isl.",
    code: '+500',
    flag: '🇬🇸',
    digits: [5],
    format: '#####',
  },
  {
    name: "Spain",
    code: '+34',
    flag: '🇪🇸',
    digits: [9],
    format: '### ### ###',
  },
  {
    name: "Sri Lanka",
    code: '+94',
    flag: '🇱🇰',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Sudan",
    code: '+249',
    flag: '🇸🇩',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Suriname",
    code: '+597',
    flag: '🇸🇷',
    digits: [6],
    format: '### ###',
  },
  {
    name: "Svalbard And Jan Mayen",
    code: '+47',
    flag: '🇸🇯',
    digits: [8],
    format: '### ## ###',
  },
  {
    name: "Swaziland",
    code: '+268',
    flag: '🇸🇿',
    digits: [8],
    format: '## ## ####',
  },
  {
    name: "Sweden",
    code: '+46',
    flag: '🇸🇪',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Switzerland",
    code: '+41',
    flag: '🇨🇭',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Syrian Arab Republic",
    code: '+963',
    flag: '🇸🇾',
    digits: [9],
    format: '## #### ###',
  },
  {
    name: "Taiwan",
    code: '+886',
    flag: '🇹🇼',
    digits: [9],
    format: '# #### ####',
  },
  {
    name: "Tajikistan",
    code: '+992',
    flag: '🇹🇯',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Tanzania",
    code: '+255',
    flag: '🇹🇿',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Thailand",
    code: '+66',
    flag: '🇹🇭',
    digits: [9],
    format: '# #### ####',
  },
  {
    name: "Timor-Leste",
    code: '+670',
    flag: '🇹🇱',
    digits: [7],
    format: '### ####',
  },
  {
    name: "Togo",
    code: '+228',
    flag: '🇹🇬',
    digits: [8],
    format: '## ### ###',
  },
  {
    name: "Tokelau",
    code: '+690',
    flag: '🇹🇰',
    digits: [4],
    format: '####',
  },
  {
    name: "Tonga",
    code: '+676',
    flag: '🇹🇴',
    digits: [5],
    format: '## ###',
  },
  {
    name: "Trinidad And Tobago",
    code: '+1',
    flag: '🇹🇹',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Tunisia",
    code: '+216',
    flag: '🇹🇳',
    digits: [8],
    format: '## ### ###',
  },
  {
    name: "Turkey",
    code: '+90',
    flag: '🇹🇷',
    digits: [10],
    format: '(###) ### ####',
  },
  {
    name: "Turkmenistan",
    code: '+993',
    flag: '🇹🇲',
    digits: [7],
    format: '# ### ###',
  },
  {
    name: "Turks And Caicos Islands",
    code: '+1',
    flag: '🇹🇨',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Tuvalu",
    code: '+688',
    flag: '🇹🇻',
    digits: [5],
    format: '## ###',
  },
  {
    name: "Uganda",
    code: '+256',
    flag: '🇺🇬',
    digits: [8, 9],
    format: '### ### ###',
  },
  {
    name: "Ukraine",
    code: '+380',
    flag: '🇺🇦',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "United Arab Emirates",
    code: '+971',
    flag: '🇦🇪',
    digits: [8],
    format: '# ### ####',
  },
  {
    name: "United Kingdom",
    code: '+44',
    flag: '🇬🇧',
    digits: [10],
    format: '## #### ####',
  },
  {
    name: "United States",
    code: '+1',
    flag: '🇺🇸',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Uruguay",
    code: '+598',
    flag: '🇺🇾',
    digits: [8],
    format: '# ### ## ##',
  },
  {
    name: "Uzbekistan",
    code: '+998',
    flag: '🇺🇿',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Vanuatu",
    code: '+678',
    flag: '🇻🇺',
    digits: [6],
    format: '## ####',
  },
  {
    name: "Venezuela",
    code: '+58',
    flag: '🇻🇪',
    digits: [10],
    format: '###-#######',
  },
  {
    name: "Viet Nam",
    code: '+84',
    flag: '🇻🇳',
    digits: [9],
    format: '## #### ###',
  },
  {
    name: "Virgin Islands, British",
    code: '+1',
    flag: '🇻🇬',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Virgin Islands, U.S.",
    code: '+1',
    flag: '🇻🇮',
    digits: [10],
    format: '(###) ###-####',
  },
  {
    name: "Wallis And Futuna",
    code: '+681',
    flag: '🇼🇫',
    digits: [6],
    format: '## ####',
  },
  {
    name: "Western Sahara",
    code: '+212',
    flag: '🇪🇭',
    digits: [9],
    format: '####-#####',
  },
  {
    name: "Yemen",
    code: '+967',
    flag: '🇾🇪',
    digits: [7],
    format: '# ### ###',
  },
  {
    name: "Zambia",
    code: '+260',
    flag: '🇿🇲',
    digits: [9],
    format: '## ### ####',
  },
  {
    name: "Zimbabwe",
    code: '+263',
    flag: '🇿🇼',
    digits: [7],
    format: '# ######',
  },

];

export const DEFAULT_COUNTRY = COUNTRIES.find(c => c.code === '+237') || COUNTRIES[0];

// Exporting these for backward compatibility if needed
export const DEFAULT_COUNTRY_CODE = DEFAULT_COUNTRY.code;
export const DEFAULT_COUNTRY_CODE_DIGITS = DEFAULT_COUNTRY.code.replace('+', '');
