import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App.tsx';
import './index.css';
// Import i18n configuration
import './i18n/config';

// Register service worker for PWA functionality
if ('serviceWorker' in navigator) {
  // Register the main PWA service worker (generated by Vite PWA)
  navigator.serviceWorker.register('/sw.js')
    .then((registration) => {
      console.log('PWA Service Worker registered successfully:', registration);
      
      // Listen for messages from the service worker
      navigator.serviceWorker.addEventListener('message', (event) => {
        if (event.data && event.data.type === 'SKIP_WAITING') {
          // Service worker is ready to activate
          window.location.reload();
        }
      });
    })
    .catch((error) => {
      console.error('PWA Service Worker registration failed:', error);
    });
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>
);
